name: SELENIUM WEBDRIVER CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the app on the runner
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    - name: Install dependencies
      run: dotnet restore SeleniumBasicExercise.sln
    - name: Build
      run: dotnet build SeleniumBasicExercise.sln --no-restore
    - name: Running TestProject1
      env:
        CHROMEWEBDRIVER: /usr/bin/google-chrome
      run: |
        echo "Running TestProject1 tests"
        dotnet test TestProject1/TestProject1.csproj --verbosity normal
    - name: Running TestProject2
      env:
        CHROMEWEBDRIVER: /usr/bin/google-chrome
      run: |
        echo "Running TestProject2 tests"
        dotnet test TestProject2/TestProject2.csproj --verbosity normal
    - name: Running TestProject3
      env:
        CHROMEWEBDRIVER: /usr/bin/google-chrome
      run: |
        echo "Running TestProject3 tests"
        dotnet test TestProject3/TestProject3.csproj --verbosity normal
